import type { AuthRouteHandler } from '../../../lib/api/routeTypes.js';
import { allStandingChallenges, standingChallenges } from '../../../lib/public/index.js';
import { testBotStatus, updateTestBot } from '../../testBot.js';
import {
  beginBotSecretRotation,
  block_player,
  checkForAbandonedGame,
  checkForTimeloss,
  createBot,
  deleteBot,
  deleteCustomization,
  deleteGames,
  endATournament,
  eventClose,
  eventCreate,
  eventCreateGames,
  eventDelete,
  eventPublish,
  eventRegister,
  eventUpdateDesc,
  eventUpdateDivisions,
  eventUpdateInvites,
  eventUpdateName,
  eventUpdateResult,
  eventUpdateStart,
  eventWithdraw,
  finalizeBotSecretRotation,
  fixGames,
  game,
  getExploration,
  getPrivateExploration,
  injectState,
  joinTournament,
  markAsPublished,
  meDashboard,
  meProfile,
  mySettings,
  newChallenge,
  newProfile,
  newSetting,
  newTournament,
  nextGame,
  onetimeFix,
  pingBot,
  purgeRetiredCompletedGames,
  respondedChallenge,
  revokeChallenge,
  saveCustomization,
  saveExploration,
  savePush,
  saveTags,
  setLastSeen,
  setPublicRivalries,
  setPush,
  startSoloGame,
  submitComment,
  submitMove,
  testAsync,
  testPush,
  toggleStar,
  unblock_player,
  updateBot,
  updateCommented,
  updateGameSettings,
  updateMetaGameCounts,
  updateNote,
  updateStanding,
  updateUserSettings,
  withdrawTournament,
  invokePie,
  deletePush,
} from '../../abstractplay.js';
import { bindAuth, bindClaims } from './shared.js';

export const coreAuthRoutes: Record<string, AuthRouteHandler> = {
  me_profile: (claims) => meProfile(claims),
  me_dashboard: (claims, pars) => meDashboard(claims, pars),
  create_bot: bindClaims(createBot),
  createBot: bindClaims(createBot),
  update_bot: bindClaims(updateBot),
  updateBot: bindClaims(updateBot),
  delete_bot: bindClaims(deleteBot),
  deleteBot: bindClaims(deleteBot),
  begin_bot_secret_rotation: bindClaims(beginBotSecretRotation),
  beginBotSecretRotation: bindClaims(beginBotSecretRotation),
  finalize_bot_secret_rotation: bindClaims(finalizeBotSecretRotation),
  finalizeBotSecretRotation: bindClaims(finalizeBotSecretRotation),
  test_bot_status: (claims) => testBotStatus(claims),
  update_test_bot: (claims, pars) => updateTestBot(claims, pars),
  next_game: (claims) => nextGame(claims.sub),
  my_settings: (claims) => mySettings(claims),
  new_setting: bindAuth(newSetting),
  new_profile: bindClaims(newProfile),
  set_push: bindAuth(setPush),
  set_public_rivalries: bindAuth(setPublicRivalries),
  save_push: bindAuth(savePush),
  delete_push: bindAuth(deletePush),
  save_tags: bindAuth(saveTags),
  save_customization: bindAuth(saveCustomization),
  delete_customization: bindAuth(deleteCustomization),
  update_standing: bindAuth(updateStanding),
  block_player: bindAuth(block_player),
  unblock_player: bindAuth(unblock_player),
  standing_challenges: (claims, pars) => standingChallenges({ ...pars, userId: claims.sub }),
  all_standing_challenges: (claims) => allStandingChallenges(claims.sub),
  new_challenge: bindAuth(newChallenge),
  challenge_revoke: bindAuth(revokeChallenge),
  challenge_response: bindAuth(respondedChallenge),
  start_solo_game: bindAuth(startSoloGame),
  submit_move: bindAuth(submitMove),
  timeloss: bindAuth(checkForTimeloss),
  abandoned: bindAuth(checkForAbandonedGame),
  invoke_pie: bindAuth(invokePie),
  update_note: bindAuth(updateNote),
  update_commented: bindAuth(updateCommented),
  set_lastSeen: bindAuth(setLastSeen),
  submit_comment: bindAuth(submitComment),
  save_exploration: bindAuth(saveExploration),
  get_exploration: bindAuth(getExploration),
  get_private_exploration: bindAuth(getPrivateExploration),
  get_game: (claims, pars) => game(claims.sub, pars),
  toggle_star: bindAuth(toggleStar),
  set_game_state: bindAuth(injectState),
  update_game_settings: bindAuth(updateGameSettings),
  update_user_settings: bindAuth(updateUserSettings),
  update_meta_game_counts: (claims) => updateMetaGameCounts(claims.sub),
  purge_retired_completed_games: (claims) => purgeRetiredCompletedGames(claims.sub),
  mark_published: bindAuth(markAsPublished),
  new_tournament: bindAuth(newTournament),
  join_tournament: bindAuth(joinTournament),
  withdraw_tournament: bindAuth(withdrawTournament),
  event_create: bindAuth(eventCreate),
  event_delete: bindAuth(eventDelete),
  event_publish: bindAuth(eventPublish),
  event_register: bindAuth(eventRegister),
  event_withdraw: bindAuth(eventWithdraw),
  event_update_start: bindAuth(eventUpdateStart),
  event_update_name: bindAuth(eventUpdateName),
  event_update_desc: bindAuth(eventUpdateDesc),
  event_update_invites: bindAuth(eventUpdateInvites),
  event_update_result: bindAuth(eventUpdateResult),
  event_update_divisions: bindAuth(eventUpdateDivisions),
  event_create_games: bindAuth(eventCreateGames),
  event_close: bindAuth(eventClose),
  ping_bot: bindAuth(pingBot),
  onetime_fix: (claims) => onetimeFix(claims.sub),
  fix_games: bindAuth(fixGames),
  test_push: (claims) => testPush(claims.sub),
  test_async: bindAuth(testAsync),
  delete_games: bindAuth(deleteGames),
  end_tournament: bindAuth(endATournament),
};
