import { headers } from '../../lib/api/http.js';
import type { ApiHandlerResult, AuthRouteHandler } from '../../lib/api/routeTypes.js';
import type { PartialClaims } from '../../lib/api/types.js';
import { testBotStatus, updateTestBot } from '../testBot.js';
import {
  allStandingChallenges,
  announcementGetAuth,
  announcementPresignUploadAuth,
  announcementPublishAuth,
  announcementReactAuth,
  announcementReactionsMineAuth,
  announcementRetractAuth,
  announcementSaveAuth,
  announcementsAdminListAuth,
  announcementsMarkReadAuth,
  beginBotSecretRotation,
  block_player,
  checkForAbandonedGame,
  checkForTimeloss,
  createBot,
  createPlaygroundSaveAuth,
  deleteBot,
  deleteCustomization,
  deleteGames,
  deletePlaygroundSaveAuth,
  deletePush,
  dismissAllNotificationsAuth,
  dismissNotificationAuth,
  endATournament,
  eventClose,
  eventCreate,
  eventCreateGames,
  eventDelete,
  eventPublish,
  eventRegister,
  eventUpdateDesc,
  eventUpdateDivisions,
  eventUpdateInvites,
  eventUpdateName,
  eventUpdateResult,
  eventUpdateStart,
  eventWithdraw,
  feedbackAdminListAuth,
  feedbackCommentAuth,
  feedbackCreateAuth,
  feedbackDeleteAuth,
  feedbackGetAuth,
  feedbackHoldRetentionAuth,
  feedbackMergeAuth,
  feedbackMineAuth,
  feedbackPresignUploadAuth,
  feedbackReclassifyAuth,
  feedbackSetAdminFieldsAuth,
  feedbackSetStatusAuth,
  feedbackSubscribeAuth,
  feedbackUpdateAuth,
  feedbackVoteAuth,
  finalizeBotSecretRotation,
  fixGames,
  game,
  getExploration,
  getPlaygroundSaveAuth,
  getPrivateExploration,
  highlightGameAuth,
  injectState,
  joinTournament,
  listNotificationsAuth,
  listPlaygroundSavesAuth,
  logLayoutEventAuth,
  logRecommendationEventAuth,
  markAsPublished,
  markNotificationsSeenAuth,
  meDashboard,
  meProfile,
  mySettings,
  newChallenge,
  newProfile,
  newSetting,
  newTournament,
  nextGame,
  onetimeFix,
  pingBot,
  purgeRetiredCompletedGames,
  recommendGameAuth,
  respondedChallenge,
  revokeChallenge,
  saveCustomization,
  saveExploration,
  savePlaygroundSaveAuth,
  savePush,
  saveTags,
  setLastSeen,
  setPublicRivalries,
  setPush,
  standingChallenges,
  startSoloGame,
  submitComment,
  submitMove,
  testAsync,
  testPush,
  toggleStar,
  unblock_player,
  unhighlightGameAuth,
  unrecommendGameAuth,
  unwatchGameAuth,
  updateBot,
  updateCommented,
  updateGameSettings,
  updateMetaGameCounts,
  updateNote,
  updateStanding,
  updateUserSettings,
  watchGameAuth,
  withdrawTournament,
  invokePie,
} from '../abstractplay.js';

const meDeprecatedResponse = (): ApiHandlerResult => ({
  statusCode: 200,
  body: JSON.stringify({
    deprecated: true,
    message: 'me is retired. Use me_profile for site-wide bootstrap and me_dashboard for the /me page.',
    useInstead: ['me_profile', 'me_dashboard'],
  }),
  headers,
});

function bindAuth(handler: (userId: string, pars: any) => Promise<ApiHandlerResult | undefined>): AuthRouteHandler {
  return (claims, pars) => handler(claims.sub, pars) as Promise<ApiHandlerResult>;
}

function bindClaims(handler: (claims: PartialClaims, pars: any) => Promise<ApiHandlerResult | undefined>): AuthRouteHandler {
  return (claims, pars) => handler(claims, pars) as Promise<ApiHandlerResult>;
}

export const authRoutes: Record<string, AuthRouteHandler> = {
  me: async () => meDeprecatedResponse(),
  me_profile: (claims) => meProfile(claims),
  me_dashboard: (claims, pars) => meDashboard(claims, pars),
  create_bot: bindClaims(createBot),
  createBot: bindClaims(createBot),
  update_bot: bindClaims(updateBot),
  updateBot: bindClaims(updateBot),
  delete_bot: bindClaims(deleteBot),
  deleteBot: bindClaims(deleteBot),
  begin_bot_secret_rotation: bindClaims(beginBotSecretRotation),
  beginBotSecretRotation: bindClaims(beginBotSecretRotation),
  finalize_bot_secret_rotation: bindClaims(finalizeBotSecretRotation),
  finalizeBotSecretRotation: bindClaims(finalizeBotSecretRotation),
  test_bot_status: (claims) => testBotStatus(claims),
  update_test_bot: (claims, pars) => updateTestBot(claims, pars),
  next_game: (claims) => nextGame(claims.sub),
  my_settings: (claims) => mySettings(claims),
  new_setting: bindAuth(newSetting),
  new_profile: bindClaims(newProfile),
  set_push: bindAuth(setPush),
  set_public_rivalries: bindAuth(setPublicRivalries),
  save_push: bindAuth(savePush),
  delete_push: bindAuth(deletePush),
  save_tags: bindAuth(saveTags),
  save_customization: bindAuth(saveCustomization),
  delete_customization: bindAuth(deleteCustomization),
  update_standing: bindAuth(updateStanding),
  block_player: bindAuth(block_player),
  unblock_player: bindAuth(unblock_player),
  standing_challenges: (claims, pars) => standingChallenges({ ...pars, userId: claims.sub }),
  all_standing_challenges: (claims) => allStandingChallenges(claims.sub),
  new_challenge: bindAuth(newChallenge),
  challenge_revoke: bindAuth(revokeChallenge),
  challenge_response: bindAuth(respondedChallenge),
  start_solo_game: bindAuth(startSoloGame),
  submit_move: bindAuth(submitMove),
  timeloss: bindAuth(checkForTimeloss),
  abandoned: bindAuth(checkForAbandonedGame),
  invoke_pie: bindAuth(invokePie),
  update_note: bindAuth(updateNote),
  update_commented: bindAuth(updateCommented),
  set_lastSeen: bindAuth(setLastSeen),
  dismiss_notification: bindAuth(dismissNotificationAuth),
  dismiss_all_notifications: (claims) => dismissAllNotificationsAuth(claims.sub),
  list_notifications: (claims) => listNotificationsAuth(claims.sub),
  mark_notifications_seen: bindAuth(markNotificationsSeenAuth),
  submit_comment: bindAuth(submitComment),
  save_exploration: bindAuth(saveExploration),
  get_exploration: bindAuth(getExploration),
  get_private_exploration: bindAuth(getPrivateExploration),
  get_game: (claims, pars) => game(claims.sub, pars),
  list_playground_saves: (claims) => listPlaygroundSavesAuth(claims.sub),
  get_playground_save: bindAuth(getPlaygroundSaveAuth),
  create_playground_save: bindAuth(createPlaygroundSaveAuth),
  save_playground_save: bindAuth(savePlaygroundSaveAuth),
  delete_playground_save: bindAuth(deletePlaygroundSaveAuth),
  toggle_star: bindAuth(toggleStar),
  watch_game: bindAuth(watchGameAuth),
  unwatch_game: bindAuth(unwatchGameAuth),
  highlight_game: bindAuth(highlightGameAuth),
  unhighlight_game: bindAuth(unhighlightGameAuth),
  recommend_game: bindAuth(recommendGameAuth),
  unrecommend_game: bindAuth(unrecommendGameAuth),
  log_recommendation_event: bindAuth(logRecommendationEventAuth),
  log_gamemove_layout_event: bindAuth(logLayoutEventAuth),
  feedback_create: bindAuth(feedbackCreateAuth),
  feedback_presign_upload: bindAuth(feedbackPresignUploadAuth),
  feedback_vote: bindAuth(feedbackVoteAuth),
  feedback_comment: bindAuth(feedbackCommentAuth),
  feedback_subscribe: bindAuth(feedbackSubscribeAuth),
  feedback_set_status: bindAuth(feedbackSetStatusAuth),
  feedback_reclassify: bindAuth(feedbackReclassifyAuth),
  feedback_update: bindAuth(feedbackUpdateAuth),
  feedback_set_admin_fields: bindAuth(feedbackSetAdminFieldsAuth),
  feedback_mine: bindAuth(feedbackMineAuth),
  feedback_admin_list: bindAuth(feedbackAdminListAuth),
  feedback_merge: bindAuth(feedbackMergeAuth),
  feedback_delete: bindAuth(feedbackDeleteAuth),
  feedback_hold_retention: bindAuth(feedbackHoldRetentionAuth),
  feedback_get: bindAuth(feedbackGetAuth),
  announcement_save: bindAuth(announcementSaveAuth),
  announcements_admin_list: bindAuth(announcementsAdminListAuth),
  announcement_get: bindAuth(announcementGetAuth),
  announcement_presign_upload: bindAuth(announcementPresignUploadAuth),
  announcement_publish: bindAuth(announcementPublishAuth),
  announcement_retract: bindAuth(announcementRetractAuth),
  announcements_mark_read: bindAuth(announcementsMarkReadAuth),
  announcement_react: bindAuth(announcementReactAuth),
  announcement_reactions_mine: bindAuth(announcementReactionsMineAuth),
  set_game_state: bindAuth(injectState),
  update_game_settings: bindAuth(updateGameSettings),
  update_user_settings: bindAuth(updateUserSettings),
  update_meta_game_counts: (claims) => updateMetaGameCounts(claims.sub),
  purge_retired_completed_games: (claims) => purgeRetiredCompletedGames(claims.sub),
  mark_published: bindAuth(markAsPublished),
  new_tournament: bindAuth(newTournament),
  join_tournament: bindAuth(joinTournament),
  withdraw_tournament: bindAuth(withdrawTournament),
  event_create: bindAuth(eventCreate),
  event_delete: bindAuth(eventDelete),
  event_publish: bindAuth(eventPublish),
  event_register: bindAuth(eventRegister),
  event_withdraw: bindAuth(eventWithdraw),
  event_update_start: bindAuth(eventUpdateStart),
  event_update_name: bindAuth(eventUpdateName),
  event_update_desc: bindAuth(eventUpdateDesc),
  event_update_invites: bindAuth(eventUpdateInvites),
  event_update_result: bindAuth(eventUpdateResult),
  event_update_divisions: bindAuth(eventUpdateDivisions),
  event_create_games: bindAuth(eventCreateGames),
  event_close: bindAuth(eventClose),
  ping_bot: bindAuth(pingBot),
  onetime_fix: (claims) => onetimeFix(claims.sub),
  fix_games: bindAuth(fixGames),
  test_push: (claims) => testPush(claims.sub),
  test_async: bindAuth(testAsync),
  delete_games: bindAuth(deleteGames),
  end_tournament: bindAuth(endATournament),
};

export async function runAuthQuery(
  queryName: string | undefined,
  claims: PartialClaims,
  pars: any,
): Promise<ApiHandlerResult> {
  const handler = queryName ? authRoutes[queryName] : undefined;
  if (!handler) {
    return {
      statusCode: 500,
      body: JSON.stringify({
        message: `Unable to execute unknown query '${queryName}'`,
      }),
      headers,
    };
  }
  const result = await handler(claims, pars);
  return result ?? {
    statusCode: 500,
    body: JSON.stringify({ message: 'Handler returned no response' }),
    headers,
  };
}
